/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // This automatically picks up all folders and files inside the /docs folder
  tutorialSidebar: [
    {
      type: 'autogenerated', 
      dirName: '.', // '.' means it will scan the entire docs folder
    },
  ],
};

export default sidebars;